# Generated by Django 3.2.7 on 2021-09-16 05:04

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=150)),
                ('about_you', models.TextField(max_length=400)),
                ('education', models.CharField(max_length=250)),
                ('career', models.CharField(max_length=150)),
                ('job_1_start', models.DateField(null=True)),
                ('job_1_end', models.DateField(null=True)),
                ('job_1_details', models.CharField(max_length=250, null=True)),
                ('job_2_start', models.DateField(null=True)),
                ('job_2_end', models.DateField(null=True)),
                ('job_2_details', models.CharField(max_length=250, null=True)),
                ('job_3_start', models.DateField(null=True)),
                ('job_3_end', models.DateField(null=True)),
                ('job_3_details', models.CharField(max_length=250, null=True)),
                ('references', models.CharField(max_length=250, null=True)),
                ('image', models.ImageField(default='user/default.png', upload_to=app.models.user_directory_path)),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
