# Generated by Django 3.2.7 on 2021-09-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
