# Generated by Django 3.2.7 on 2021-09-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='job_1_details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_1_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_1_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_2_details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_2_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_2_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_3_details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_3_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_3_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='references',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
