# Generated by Django 3.2.7 on 2021-09-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210915_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='job_1_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_2_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_2_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_3_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_3_start',
            field=models.DateField(null=True),
        ),
    ]
