# Generated by Django 3.2.7 on 2021-09-16 08:35

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_resume_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(default='user/default.jpg', upload_to=app.models.user_directory_path),
        ),
    ]
