# Generated by Django 3.2.7 on 2021-09-16 04:42

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20210915_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(default='user/default.png', upload_to=app.models.user_directory_path),
        ),
    ]
